### ISSUE TITLE
Uncaught std::stoi error

### ISSUE THREAD

**Issue by WinXPDev** [Jaysmito101/tovie#2]
In the file [toviec.cpp line 26](https://github.com/Jaysmito101/tovie/blob/695455a516682c15fede87e187e0701c79a2067c/src/toviec.cpp#L26), it show that you don't handle the std::stoi error about large number (std::out_of_range)
```cpp
operations.push_back(Operation(OperationType::PUSH, std::stoi(token)));
```

The input file:
```
99999999999999
```

Solution:
1 - Try handle it and give the user error about integer too big

2 - Use multiprecision library such as mpir or boost.multiprecision

__Note: multiprecision maybe slower than pure int__

**Comment by Jaysmito101** [comment]
> In the file [toviec.cpp line 26](https://github.com/Jaysmito101/tovie/blob/695455a516682c15fede87e187e0701c79a2067c/src/toviec.cpp#L26), it show that you don't handle the std::stoi error about large number (std::out_of_range)
> 
> ```c++
> operations.push_back(Operation(OperationType::PUSH, std::stoi(token)));
> ```
> 
> The input file:
> 
> ```
> 99999999999999
> ```
> 
> Solution: 1 - Try handle it and give the user error about integer too big
> 
> 2 - Use multiprecision library such as mpir or boost.multiprecision
> 
> **Note: multiprecision maybe slower than pure int**

In will give too bin int error but not multi precision. It will be fixed in next commit!

**Comment by Jaysmito101** [comment]
Fixed https://github.com/Jaysmito101/tovie/commit/07785ebe65340cba165b14d9bf642b65a860b1fe
